In [1]:
import torch

# Check if MPS is available
if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    # Example tensor operations on MPS
    x = torch.ones(5, device=mps_device)
    y = torch.ones(5, device=mps_device)
    z = x + y
    print(z)


tensor([2., 2., 2., 2., 2.], device='mps:0')


In [2]:
import torch

# Check if MPS is available
mps_available = torch.backends.mps.is_available()
print("MPS is available:", mps_available)

if mps_available:
    # Create a tensor on the MPS device and perform an operation
    mps_device = torch.device("mps")
    x = torch.ones(5, device=mps_device)
    y = torch.ones(5, device=mps_device)
    z = x + y
    print(z)
else:
    print("MPS is not available. Please ensure your PyTorch installation supports it.")


MPS is available: True
tensor([2., 2., 2., 2., 2.], device='mps:0')


In [3]:
import torch
import torch.nn as nn
import torch.optim as optim

# Check if MPS is available
device = torch.device("mps") if torch.backends.mps.is_available() else torch.device("cpu")

# Define a simple neural network
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(10, 50)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(50, 1)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return x

# Create a model instance and move it to the MPS device
model = SimpleNN().to(device)

# Define a loss function and optimizer
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Dummy data for demonstration
inputs = torch.randn(10, device=device)
target = torch.randn(1, device=device)

# Training step
optimizer.zero_grad()
outputs = model(inputs)
loss = criterion(outputs, target)
loss.backward()
optimizer.step()

print(f"Loss: {loss.item()}")


Loss: 11.744558334350586


In [4]:
import torch
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1


## Introduction to Tensors

#### tensors `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html


In [5]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [8]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
matrix.ndim

2

In [13]:
matrix[1]

tensor([ 9, 10])

In [14]:
matrix.shape

torch.Size([2, 2])

In [15]:
TENSOR = torch.tensor([[[7,8,12],[9,10,11],[9,10,11]]])
TENSOR

tensor([[[ 7,  8, 12],
         [ 9, 10, 11],
         [ 9, 10, 11]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[ 7,  8, 12],
        [ 9, 10, 11],
        [ 9, 10, 11]])

In [19]:
random_number = torch.rand(2,3,4)
random_number

tensor([[[0.1449, 0.6905, 0.3142, 0.1164],
         [0.0188, 0.2683, 0.5306, 0.1750],
         [0.4062, 0.4238, 0.2843, 0.8297]],

        [[0.5376, 0.8814, 0.5748, 0.5393],
         [0.8934, 0.3597, 0.5054, 0.0430],
         [0.6985, 0.3880, 0.9665, 0.0664]]])

In [20]:
random_number.ndim

3

In [21]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [22]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
zeros*random_number

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [24]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

In [26]:
one_to_ten = torch.arange(start=0,step=10, end=100)
one_to_ten

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [27]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# tensor datatypes

In [28]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_16_tensor.dtype

torch.float16

In [32]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [33]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [34]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

In [35]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5301, 0.2477, 0.0061, 0.6701],
        [0.4639, 0.4577, 0.0296, 0.5758],
        [0.7946, 0.0269, 0.4801, 0.1036]])

In [36]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"shape of tensor:{some_tensor.shape}")
print(f"size of tensor:{some_tensor.size()}")
print(f"device of tensor:{some_tensor.device}")

tensor([[0.5301, 0.2477, 0.0061, 0.6701],
        [0.4639, 0.4577, 0.0296, 0.5758],
        [0.7946, 0.0269, 0.4801, 0.1036]])
Datatype of tensor: torch.float32
shape of tensor:torch.Size([3, 4])
size of tensor:torch.Size([3, 4])
device of tensor:cpu


In [37]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [38]:
tensor * 10


tensor([10, 20, 30])

In [39]:
tensor - 10

tensor([-9, -8, -7])

In [40]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [41]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [42]:
print(f"Elemet wise multiplication:{tensor * tensor}")

Elemet wise multiplication:tensor([1, 4, 9])


In [43]:
torch.matmul(tensor , tensor)

tensor(14)

In [44]:
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)


In [45]:
tensor @ tensor

tensor(14)

In [46]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[1.2927, 1.7634, 0.6061],
        [1.1223, 1.5900, 0.5418],
        [0.6835, 1.1120, 0.3678]])

In [47]:
tensorA = torch.tensor([[1, 2],[3, 4], [5, 6]])
tensorB = torch.tensor([[7,8],[9,10],[11,12]])

In [48]:
torch.matmul(tensorA.T, tensorB)

tensor([[ 89,  98],
        [116, 128]])

In [49]:
tensorA.shape, tensorB.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [50]:
tensorB.T, tensorB.T.shape


(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [51]:
print(tensorA
,tensorB
,tensorA.shape
,tensorB.shape
,tensorA.T
,tensorB.T
,tensorA.T.shape
,tensorB.T.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6]]) tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]]) torch.Size([3, 2]) torch.Size([3, 2]) tensor([[1, 3, 5],
        [2, 4, 6]]) tensor([[ 7,  9, 11],
        [ 8, 10, 12]]) torch.Size([2, 3]) torch.Size([2, 3])


In [52]:
torch.mm(tensorA
,tensorB.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [53]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [54]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [55]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [56]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [57]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [58]:
x.argmin()

tensor(0)

In [59]:
x[0]

tensor(0)

In [60]:
x.argmax()

tensor(9)

# stack

In [67]:
a = torch.arange(1,13)
a, a.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), torch.Size([12]))

In [68]:
a_reshaped = a.reshape(3,4)
a_reshaped , a_reshaped.shape

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 torch.Size([3, 4]))