In [1]:
import torch

# Check if MPS is available
if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    # Example tensor operations on MPS
    x = torch.ones(5, device=mps_device)
    y = torch.ones(5, device=mps_device)
    z = x + y
    print(z)


In [2]:
import torch

# Check if MPS is available
mps_available = torch.backends.mps.is_available()
print("MPS is available:", mps_available)

if mps_available:
    # Create a tensor on the MPS device and perform an operation
    mps_device = torch.device("mps")
    x = torch.ones(5, device=mps_device)
    y = torch.ones(5, device=mps_device)
    z = x + y
    print(z)
else:
    print("MPS is not available. Please ensure your PyTorch installation supports it.")


MPS is available: False
MPS is not available. Please ensure your PyTorch installation supports it.


In [3]:
import torch
import torch.nn as nn
import torch.optim as optim

# Check if MPS is available
device = torch.device("mps") if torch.backends.mps.is_available() else torch.device("cpu")

# Define a simple neural network
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(10, 50)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(50, 1)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return x

# Create a model instance and move it to the MPS device
model = SimpleNN().to(device)

# Define a loss function and optimizer
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Dummy data for demonstration
inputs = torch.randn(10, device=device)
target = torch.randn(1, device=device)

# Training step
optimizer.zero_grad()
outputs = model(inputs)
loss = criterion(outputs, target)
loss.backward()
optimizer.step()

print(f"Loss: {loss.item()}")


Loss: 0.857847273349762


In [4]:
import torch
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu117


## Introduction to Tensors

#### tensors `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html


In [5]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [8]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
matrix.ndim

2

In [13]:
matrix[1]

tensor([ 9, 10])

In [14]:
matrix.shape

torch.Size([2, 2])

In [15]:
TENSOR = torch.tensor([[[7,8,12],[9,10,11],[9,10,11]]])
TENSOR

tensor([[[ 7,  8, 12],
         [ 9, 10, 11],
         [ 9, 10, 11]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[ 7,  8, 12],
        [ 9, 10, 11],
        [ 9, 10, 11]])

In [19]:
random_number = torch.rand(2,3,4)
random_number

tensor([[[0.0993, 0.8188, 0.5130, 0.7911],
         [0.9301, 0.9140, 0.6900, 0.0897],
         [0.5208, 0.4388, 0.5012, 0.6274]],

        [[0.9121, 0.2729, 0.0014, 0.6074],
         [0.0129, 0.5264, 0.2202, 0.6765],
         [0.1506, 0.7194, 0.4931, 0.3127]]])

In [20]:
random_number.ndim

3

In [21]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [22]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
zeros*random_number

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [24]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

In [26]:
one_to_ten = torch.arange(start=0,step=10, end=100)
one_to_ten

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [27]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# tensor datatypes

In [28]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_16_tensor.dtype

torch.float16

In [32]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [33]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [34]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

In [35]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7836, 0.7125, 0.7457, 0.3531],
        [0.6320, 0.3636, 0.6300, 0.8284],
        [0.1104, 0.7646, 0.8925, 0.7048]])

In [36]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"shape of tensor:{some_tensor.shape}")
print(f"size of tensor:{some_tensor.size()}")
print(f"device of tensor:{some_tensor.device}")

tensor([[0.7836, 0.7125, 0.7457, 0.3531],
        [0.6320, 0.3636, 0.6300, 0.8284],
        [0.1104, 0.7646, 0.8925, 0.7048]])
Datatype of tensor: torch.float32
shape of tensor:torch.Size([3, 4])
size of tensor:torch.Size([3, 4])
device of tensor:cpu


In [37]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [38]:
tensor * 10


tensor([10, 20, 30])

In [39]:
tensor - 10

tensor([-9, -8, -7])

In [40]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [41]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [42]:
print(f"Elemet wise multiplication:{tensor * tensor}")

Elemet wise multiplication:tensor([1, 4, 9])


In [43]:
torch.matmul(tensor , tensor)

tensor(14)

In [44]:
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)


In [45]:
tensor @ tensor

tensor(14)

In [46]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[1.3365, 1.4482, 1.0077],
        [0.7477, 0.7145, 0.5782],
        [1.2126, 1.2840, 0.9188]])

In [47]:
tensorA = torch.tensor([[1, 2],[3, 4], [5, 6]])
tensorB = torch.tensor([[7,8],[9,10],[11,12]])

In [48]:
torch.matmul(tensorA.T, tensorB)

tensor([[ 89,  98],
        [116, 128]])

In [49]:
tensorA.shape, tensorB.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [50]:
tensorB.T, tensorB.T.shape


(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [51]:
print(tensorA
,tensorB
,tensorA.shape
,tensorB.shape
,tensorA.T
,tensorB.T
,tensorA.T.shape
,tensorB.T.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6]]) tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]]) torch.Size([3, 2]) torch.Size([3, 2]) tensor([[1, 3, 5],
        [2, 4, 6]]) tensor([[ 7,  9, 11],
        [ 8, 10, 12]]) torch.Size([2, 3]) torch.Size([2, 3])


In [52]:
torch.mm(tensorA
,tensorB.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [53]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [54]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [55]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [56]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [57]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [58]:
x.argmin()

tensor(0)

In [59]:
x[0]

tensor(0)

In [60]:
x.argmax()

tensor(9)

# stack

In [61]:
a = torch.arange(1,13)
a, a.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), torch.Size([12]))

In [62]:
a_reshaped = a.reshape(3,4)
a_reshaped , a_reshaped.shape

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 torch.Size([3, 4]))

In [63]:
x = torch.arange(1,11)
x,x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [64]:
x_reshaped = x.reshape(1,10)
x_reshaped, x_reshaped.shape


(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]))

In [65]:
z = x.view(1,10)
z,z.shape


(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]))

In [66]:
z[:,0] = 5
z,x

(tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [67]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[ 5,  5,  5,  5],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [ 5,  5,  5,  5],
        [ 6,  6,  6,  6],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 9,  9,  9,  9],
        [10, 10, 10, 10]])

In [68]:
x_reshaped.shape

torch.Size([1, 10])

In [69]:
x_reshaped.squeeze().shape

torch.Size([10])

In [70]:
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)

In [72]:
x_original = torch.rand(size=(224,224,3))
x_permuted = x_original.permute(2,0,1)
print(f"previous shape: {x_original.shape}")
print(f"premuted shape: {x_permuted.shape}")


previous shape: torch.Size([224, 224, 3])
premuted shape: torch.Size([3, 224, 224])


In [73]:
x_original[0,0,0] = 1
x_original[0,0,0],x_permuted[0,0,0]

(tensor(1.), tensor(1.))

In [74]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [75]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [76]:
x[0,0]

tensor([1, 2, 3])

In [77]:
x[0,0,0]

tensor(1)

In [78]:
x[0][0]

tensor([1, 2, 3])

In [79]:
x[:,1]

tensor([[4, 5, 6]])

In [80]:
x[:,:,1]

tensor([[2, 5, 8]])

In [81]:
x[:,1,1]

tensor([5])

In [82]:
x[:,1,:]

tensor([[4, 5, 6]])

In [83]:
x[:,:,:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [84]:
x[0,2,2]

tensor(9)

In [85]:
x[:,:,2]

tensor([[3, 6, 9]])

In [87]:
import torch
print(torch.__version__)


2.0.1+cu117


In [88]:
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [89]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [90]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)

print(random_tensor_B)

print(random_tensor_A == random_tensor_B)

tensor([[0.6537, 0.7928, 0.4832, 0.5618],
        [0.9107, 0.1829, 0.5577, 0.8322],
        [0.4473, 0.4747, 0.6939, 0.6371]])
tensor([[0.6358, 0.2814, 0.4201, 0.1025],
        [0.1054, 0.0141, 0.8539, 0.3171],
        [0.0423, 0.0759, 0.1114, 0.7137]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [91]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)

random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)

print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [92]:
!nvidia-smi

Thu Aug 29 16:02:13 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.85                 Driver Version: 555.85         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1050 Ti   WDDM  |   00000000:01:00.0  On |                  N/A |
|  0%   40C    P8             N/A /   75W |     657MiB /   4096MiB |     10%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [93]:
torch.cuda.is_available()

True

In [94]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [95]:
torch.cuda.device_count()

1