In [5]:
import torch

# Check if MPS is available
if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    # Example tensor operations on MPS
    x = torch.ones(5, device=mps_device)
    y = torch.ones(5, device=mps_device)
    z = x + y
    print(z)


tensor([2., 2., 2., 2., 2.], device='mps:0')


In [6]:
import torch

# Check if MPS is available
mps_available = torch.backends.mps.is_available()
print("MPS is available:", mps_available)

if mps_available:
    # Create a tensor on the MPS device and perform an operation
    mps_device = torch.device("mps")
    x = torch.ones(5, device=mps_device)
    y = torch.ones(5, device=mps_device)
    z = x + y
    print(z)
else:
    print("MPS is not available. Please ensure your PyTorch installation supports it.")


MPS is available: True
tensor([2., 2., 2., 2., 2.], device='mps:0')


In [7]:
import torch
import torch.nn as nn
import torch.optim as optim

# Check if MPS is available
device = torch.device("mps") if torch.backends.mps.is_available() else torch.device("cpu")

# Define a simple neural network
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(10, 50)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(50, 1)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return x

# Create a model instance and move it to the MPS device
model = SimpleNN().to(device)

# Define a loss function and optimizer
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Dummy data for demonstration
inputs = torch.randn(10, device=device)
target = torch.randn(1, device=device)

# Training step
optimizer.zero_grad()
outputs = model(inputs)
loss = criterion(outputs, target)
loss.backward()
optimizer.step()

print(f"Loss: {loss.item()}")


Loss: 0.089787557721138


In [8]:
import torch
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

## Introduction to Tensors

#### tensors `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html


In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[1]

tensor([ 9, 10])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[7,8,12],[9,10,11],[9,10,11]]])
TENSOR

tensor([[[ 7,  8, 12],
         [ 9, 10, 11],
         [ 9, 10, 11]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[ 7,  8, 12],
        [ 9, 10, 11],
        [ 9, 10, 11]])

In [ ]:
random_number = torch.rand(2,3,4)
random_number

tensor([[[0.7103, 0.3919, 0.0079, 0.5174],
         [0.9743, 0.2929, 0.3401, 0.0141],
         [0.9692, 0.3706, 0.0957, 0.4803]],

        [[0.6653, 0.7549, 0.9077, 0.9345],
         [0.1292, 0.9557, 0.5773, 0.7349],
         [0.5130, 0.2228, 0.9848, 0.1452]]])

In [ ]:
random_number.ndim

3

In [ ]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_number

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
one_to_ten = torch.arange(start=0,step=10, end=100)
one_to_ten

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# tensor datatypes

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor.dtype

torch.float16

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7094, 0.6903, 0.2801, 0.9994],
        [0.5562, 0.1222, 0.3665, 0.8250],
        [0.7123, 0.7869, 0.9179, 0.0979]])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"shape of tensor:{some_tensor.shape}")
print(f"size of tensor:{some_tensor.size()}")
print(f"device of tensor:{some_tensor.device}")

tensor([[0.7094, 0.6903, 0.2801, 0.9994],
        [0.5562, 0.1222, 0.3665, 0.8250],
        [0.7123, 0.7869, 0.9179, 0.0979]])
Datatype of tensor: torch.float32
shape of tensor:torch.Size([3, 4])
size of tensor:torch.Size([3, 4])
device of tensor:cpu


In [ ]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10


tensor([10, 20, 30])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [ ]:
print(f"Elemet wise multiplication:{tensor * tensor}")

Elemet wise multiplication:tensor([1, 4, 9])


In [ ]:
torch.matmul(tensor , tensor)

tensor(14)

In [ ]:
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)


In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.2732, 0.5124, 1.1483],
        [0.2536, 0.4752, 1.0654],
        [0.2779, 0.5367, 1.1823]])

In [ ]:
tensorA = torch.tensor([[1, 2],[3, 4], [5, 6]])
tensorB = torch.tensor([[7,8],[9,10],[11,12]])

In [ ]:
torch.matmul(tensorA.T, tensorB)

tensor([[ 89,  98],
        [116, 128]])

In [ ]:
tensorA.shape, tensorB.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
tensorB.T, tensorB.T.shape


(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [ ]:
print(tensorA
,tensorB
,tensorA.shape
,tensorB.shape
,tensorA.T
,tensorB.T
,tensorA.T.shape
,tensorB.T.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6]]) tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]]) torch.Size([3, 2]) torch.Size([3, 2]) tensor([[1, 3, 5],
        [2, 4, 6]]) tensor([[ 7,  9, 11],
        [ 8, 10, 12]]) torch.Size([2, 3]) torch.Size([2, 3])


In [ ]:
torch.mm(tensorA
,tensorB.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [ ]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
x.argmax()

tensor(9)

# stack

In [ ]:
a = torch.arange(1,13)
a, a.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), torch.Size([12]))

In [ ]:
a_reshaped = a.reshape(3,4)
a_reshaped , a_reshaped.shape

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 torch.Size([3, 4]))

In [ ]:
x = torch.arange(1,11)
x,x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [ ]:
x_reshaped = x.reshape(1,10)
x_reshaped, x_reshaped.shape


(tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]))

In [ ]:
z = x.view(1,10)
z,z.shape


(tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]))

In [ ]:
z[:,0] = 5
z,x

(tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[ 5,  5,  5,  5],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [ 5,  5,  5,  5],
        [ 6,  6,  6,  6],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 9,  9,  9,  9],
        [10, 10, 10, 10]])

In [ ]:
x_reshaped.shape

torch.Size([1, 10])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([10])

In [ ]:
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)

tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [ ]:
x_original = torch.rand(size=(224,224,3))
x_permuted = x_original.permute(2,0,1)
print(f"previous shape: {x_original.shape}")
print(f"premuted shape: {x_permuted.shape}")


previous shape: torch.Size([224, 224, 3])
premuted shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0,0,0] = 1
x_original[0,0,0],x_permuted[0,0,0]

(tensor(1.), tensor(1.))

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0,0]

tensor([1, 2, 3])

In [ ]:
x[0,0,0]

tensor(1)

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[:,1]

tensor([[4, 5, 6]])

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
x[:,1,1]

tensor([5])

In [ ]:
x[:,1,:]

tensor([[4, 5, 6]])

In [ ]:
x[:,:,:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0,2,2]

tensor(9)

In [ ]:
x[:,:,2]

tensor([[3, 6, 9]])

In [ ]:
import torch
print(torch.__version__)
%pip install torch==2.3.1 numpy --upgrade

2.3.1
  Using cached numpy-2.1.0-cp310-cp310-macosx_14_0_arm64.whl.metadata (60 kB)
Using cached numpy-2.1.0-cp310-cp310-macosx_14_0_arm64.whl (5.4 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.5
    Uninstalling numpy-1.23.5:
      Successfully uninstalled numpy-1.23.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
d2l 1.0.3 requires numpy==1.23.5, but you have numpy 2.1.0 which is incompatible.
d2l 1.0.3 requires requests==2.31.0, but you have requests 2.32.3 which is incompatible.
scipy 1.10.1 requires numpy<1.27.0,>=1.19.5, but you have numpy 2.1.0 which is incompatible.
tensorflow 2.16.2 requires numpy<2.0.0,>=1.23.5; python_version <= "3.11", but you have numpy 2.1.0 which is incompatible.
Note: you may need to restart the kernel to use updated packages.


In [ ]:
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)

print(random_tensor_B)

print(random_tensor_A == random_tensor_B)

tensor([[0.8568, 0.8731, 0.5600, 0.3490],
        [0.0645, 0.6710, 0.0467, 0.9528],
        [0.7069, 0.0117, 0.4251, 0.1458]])
tensor([[0.4393, 0.2333, 0.8687, 0.7471],
        [0.3650, 0.2029, 0.1576, 0.2433],
        [0.8017, 0.7249, 0.4307, 0.9941]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)

random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)

print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
